### ISSUE TITLE
i'll get lower fps

### ISSUE THREAD

**Issue by yatmanyatan** [kevinatown/MMM-Screencast#17]
please help me it still freezes

**Comment by kevinatown** [comment]
Hey, 

What actually happens when it freezes? Are you able to cast to the device? Can you collect some logs, so that I will have a better idea of what is going on. Run the app like:

```
display=:0 npm start >> log.log
```

And attempt to cast to the pi, let it play (or freeze) for a bit, stop the cast, and then stop the app and send me the created file: `log.log`. 

thanks!

**Comment by yatmanyatan** [comment]
it doesn't like a bug it's seems like this video https://www.youtube.com/watch?v=hDaBgVPXIyw 00:06

**Comment by kevinatown** [comment]
hey @yatmanyatan I am going to close this issue as you think it isn’t a bug, feel free to reopen it or another one if you have any more issues.
