### ISSUE TITLE
Not working....

### ISSUE THREAD

**Issue by fawazymohsin** [kevinatown/MMM-Screencast#36]
So when I run npm install, 12 vulnerabilities are found. My phone recognized the raspberry pi but when I click to connect, my phone just displays "connecting" and it never appears on my pi. I've tried npm audit fix, but it doesn't let me fix the dependencies unless I do it manually. 

Any idea on how you can help me ?

**Comment by lubell16** [comment]
I am getting the same error. Were you able to solve it?

**Comment by kevinatown** [comment]
Hey @fawazymohsin and @lubell16!

Sorry about the delay on getting back to y'all, Ive been really busy. Anyways, the "npm install, 12 vulnerabilities", shouldn't have any affect on MMM-Screencast, it's mostly letting you know that the version of electron required is vulnerable. I'll try to update it, so that this warning goes away.

As for your actual issue, do y'all happen to have anymore information? Or potentially logs from the MM? If not could you run:

```bash
display=:0 npm start >> log.log
```

Allow the MM to start up then attempt to connect, connect, disconnect and then send the log.log contents here?

**Comment by lubell16** [comment]
Hey @kevinatown 
I realized this and ended up getting it to work if I removed MMM-Spotify player and loaded that in after. I love the module but quick question.
When I first start casting it sounds choppy for 20 ish seconds or I can wait 20 seconds before hitting play. Is there a way to get it not to sound choppy for the first 20 seconds? If not no big deal I can just let it pause before playing anything

**Comment by WolfShadowheart** [comment]
Hi, I have been unable to get this working as well. I force installed the npm dependencies, however config/config.js never appears, thus I cannot edit the file to add the array. 

I am also new to this, however I have followed the instructions exactly.

**Comment by WolfShadowheart** [comment]
Aha, so I have figured out my issue. config.js does not lie within the modules, rather under MagicMirror/config

**Comment by WolfShadowheart** [comment]
I have also been prompted for a new npm update after resolving an mmpm
[as referenced here](https://github.com/Bee-Mar/mmpm/issues/5#issuecomment-513429374).

After it installed, I began using CLI mmpm to install various packages, and after I install MMM-pages, i was prompted with an npm update from 6.9.0 to 6.11.2, asking that I run 

     npm install -g npm

I did so without sudo and needed write access, so I did so once more with sudo. 

I will edit this comment if it seems to resolve the issue!
