### ISSUE TITLE
Javascript error.

### ISSUE THREAD

**Issue by Bernard-h** [kevinatown/MMM-Screencast#55]
Hi I tried this, but it doesnt work please see the javascript error which is displayed on my mirror when I cast.
![Schermafbeelding 2020-02-06 om 22 51 32](https://user-images.githubusercontent.com/60395872/73981798-58313100-4933-11ea-893b-51de21f8858d.png)

**Comment by robertalexa** [comment]
same here @kevinatown any fixes on this?

**Comment by kevinatown** [comment]
Hey @Bernard-h and @robertalexa! So generally this error is due to a config issue with MMM-Screencast within the MM. It is most likely an issue with using MM's positions instead of MMM-Screencast's `['bottomRight', 'bottomCenter', 'bottomLeft', 'center', 'topRight', 'topCenter', 'topLeft']`.

If y'all can attach (with all API keys removed) your config.js to this issue I can take a look and see if there is anything that stands out.

**Comment by robertalexa** [comment]
> Hey @Bernard-h and @robertalexa! So generally this error is due to a config issue with MMM-Screencast within the MM. It is most likely an issue with using MM's positions instead of MMM-Screencast's `['bottomRight', 'bottomCenter', 'bottomLeft', 'center', 'topRight', 'topCenter', 'topLeft']`.
> 
> If y'all can attach (with all API keys removed) your config.js to this issue I can take a look and see if there is anything that stands out.

Hi Kevin

You are right. I did not notice the positions are not the default MM positions. Doh. guess being tired is not good.

**Comment by Bernard-h** [comment]
I just reloaded this and changed my position to center.. it works fine. Really weird , im 1000% sure i tested different position and sizes. Anyway this works. Closing issue , since Kevin has his fixed as well.
