### ISSUE TITLE
Screencast loads on MM - then freezes

### ISSUE THREAD

**Issue by hutny1980** [kevinatown/MMM-Screencast#7]
Hi,

Installed the Screencast Module today and have tried to cast from 2 different iPhones - the screencast module loads the Youtube video on the Magic Mirror, but it freezes on the first frame and won't play the video.

I've tried casting on two different iPhones, but with no luck and the sames symptoms on both devices. Magic Mirror is running on RPi 3 and iPhones I'm casting from are on the same Wifi network. Here are the output of the logs I've captured. The first log output is when I start the cast to the Magic Mirror and the second log output is when I cancel the cast.

**Log Output 1 - Starting the cast**
0|mm       | screencast stdout:
0|mm       | > magicmirror-screencast@0.0.1 start /home/pi/MagicMirror/modules/MMM-Screencast
0|mm       | > electron app.js "http://www.youtube.com/tv?pairingCode=BF5A6013-8AB5-47DD-A820-018A6E2C566F&rUrl=ws%3A%2F%2F192.168.1.9%3A57364%2FD214526C-AEE8-4E7E-8100-8AAA59226DEE&rId=C641178A-655D-41CE-9FBC-8BC16A9C1008&t=7.1&theme=cl&v=BAYOqpNbFeo" "bottomRight" "500" "300"
0|mm       | screencast stdout: Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.screenCastWindow
0|mm       | screencast stdout: starting server on  /tmp/app.screenCastWindow
0|mm       | starting TLS server false
0|mm       | starting server as Unix || Windows Socket

**Log Output 2 - Stopping the cast**
Got request to stop YouTube  with pid:  run
0|mm       | Service path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + id
0|mm       | requested connection to  screenCastWindow /tmp/app.screenCastWindow
0|mm       | Connecting client on Unix Socket : /tmp/app.screenCastWindow
0|mm       | screencast stdout: ## socket connection to server detected ##
0|mm       | dispatching event to  screenCastWindow /tmp/app.screenCastWindow  :  quit ,
0|mm       | retrying reset
0|mm       | screencast stdout: received event of :  quit {}
0|mm       | dispatching event to socket  :  quit
0|mm       | ## received events ##
0|mm       | detected event quit {}
0|mm       | connection closed screenCastWindow /tmp/app.screenCastWindow Infinity tries remaining of Infinity
0|mm       | screenCastDIAL exceeded connection rety amount of  or stopRetrying flag set.
0|mm       | screencast stdout: socket disconnected false
0|mm       | closing code: 0

Any help and advice would be hugely appreciated.

Thanks,
G

**Comment by hutny1980** [comment]
@kevinatown - sorry to bump, but any help would bee appreciated?

**Comment by kevinatown** [comment]
Hey G, so sorry about the delay! I've been swamped with the holidays and starting a new job. Overall nothing looks off about the logs you posted. I would need some more information to determine what is going on. 

- Is there any other logs under the ones you sent?
- When you cancel the cast, does the window actually disappear?
- How many other modules (and what modules) are you running on your MM/is there anything else you are running on the pi?

I'll try and keep up with this issue so that we can get it solved for ya!

**Comment by hutny1980** [comment]
No problem @kevinatown - I really appreciate your help!! 

Answers to your questions:

- Is there any other logs under the ones you sent? **[GH] No - just what I sent. The window loads and I can see the first frame with the standard spinning Youtube loading circle**
- When you cancel the cast, does the window actually disappear? **[GH] Yes, the window disappears when I cancel the cast.**
- How many other modules (and what modules) are you running on your MM/is there anything else you are running on the pi? **[GH] This is what I currently have installed:**

Magic Mirror Modules Installed:
* MMM-Strava
* MMM-Traffic
* MMM-WunderGround
* MMM-Todoist
* MMM-SoccerLiveScore
* MMM-Mail

Other Software Installed:
* Shairport-Sync (Adds Airplay Streaming Capibility)
* Google Assistant SDK Library 
* Webmin
* Mosquitto MTQQ Server

Thanks again for all your help.

G

**Comment by hutny1980** [comment]
@kevinatown - I thought it was worth sharing my Screencast entry in the Config.js file, just to make sure I'd not missed something in there. 

{
                module: 'MMM-Screencast',
                position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
                config: {
                        position: 'bottomRight',
                        height: 300,
                        width: 500,
                }
        },

**Comment by kevinatown** [comment]
Hmmm, so nothing looks out of the ordinary in the configs or the screenshot. I see a couple potential problems.

1. In the screenshot you sent me it looks like the video is buffering? What happens if you pause it and let it load? Does the spinner continue to spin? Does any sound/video happen?

2. There could be something getting in the way with shareport-sync, Webmin, or Mosquitto MTQQ. Like fighting for ports (I doubt this as something should just fail if the port was taken), cpu usage, memory, or network bandwidth. We can run some simple tests to ensure that it's not memory, cpu, and watch all network traffic.

So to run both of these, you will need to open two more terminal windows, run one command in each, and then run the MM, try to cast, wait a bit while nothing happens, and stop the cast. After which send me the created files and I can take a look and see if anything odd is happening.

Run the network watch:
```
netstat -lptnc > netStat.txt
```

Run the cpu/memory watch:
```
top -stats command,cpu,mem -o mem -O cpu > topResults.txt
```

Sorry about all of the hassle, but hopefully there will be something we can do to fix this. Good Luck!

**Comment by manojjenago** [comment]
Hi kevin,

I want to get the URL like Iphone provides 
( electron app.js "http://www.youtube.com/tv?pairingCode=BF5A6013-8AB5-47DD-A820-018A6E2C566F&rUrl=ws%3A%2F%2F192.168.1.9%3A57364%2FD214526C-AEE8-4E7E-8100-8AAA59226DEE&rId=C641178A-655D-41CE-9FBC-8BC16A9C1008&t=7.1&theme=cl&v=BAYOqpNbFeo" ) in Android (Nexus) But the URL looks different and does not have the v="" which I believe the ID of the Video ... how it plays in OMXPlayer from android then ??

**Comment by kevinatown** [comment]
Hey MKJ, I'll answer this question in the your open issue.
