### ISSUE TITLE
Pi not showing up in youtube app

### ISSUE THREAD

**Issue by shotbyapony** [kevinatown/MMM-Screencast#70]
```
config: {
			module: 'MMM-Screencast',
			position: 'bottom_right', 
			config: {
				position: 'bottom_right',
				height: 300,
				width: 500,
				castName: 'Magic Mirror'
			}
		},
```

fresh install, before it would show up but say X wasn't defined so I deleted the screencast folder and redownloaded/installed it. Any help? TIA

**Comment by kevinatown** [comment]
Hey @shotbyapony! Sorry bout the issue, so what do you mean by `say X wasn't defined`?

Also can you please do the following:
- send me a complete copy of your config (with all api keys removed)
- what are you running this on? (raspberry version? linux distro? etc? (whatever hardware info you can give))
- run the MagicMirror with a logging and send it to me. run (in the MM root dir):
```
display=:0 npm start >> log.log
```
and place the log file in this chat. 

Thanks!!

**Comment by shotbyapony** [comment]
[Error](http://imgur.com/a/yYmPh06)
this happens when i attempt to cast (it only showed up once, it no longer shows up.)

[log](https://pastebin.com/90ZaEArU)

[config](https://pastebin.com/AZpw9hBE)

**Comment by kevinatown** [comment]
So the issue here is that in your config for MMM-Screencast you are using snake case for the position, according to the docs on the (README)[https://github.com/kevinatown/MMM-Screencast/blob/master/README.md] you should use camel case, i.e `bottomRight` instead of `bottom_right`. This should fit the issues of the MMM-Screencast not showing up.

I'm going to close this issue, but feel free to reopen it or open another one if this doesn't work/you have more questions.
