### ISSUE TITLE
JavaScript Error Occurred in the main process

### ISSUE THREAD

**Issue by cluelesscarter** [kevinatown/MMM-Screencast#85]
Hey - had a little trouble getting this to show up in the casting list, but after a reboot it did. Now I'm recieving this issue:

![image](https://user-images.githubusercontent.com/26582942/91737455-04c05200-eba7-11ea-86d8-f182266b0713.png)

**Module Config:**
```
{
		module: 'MMM-Screencast',
		position: 'middle', // This position is for a hidden <div /> and not the screencast window
		config: {
			position: 'middle',
			height: 300,
			width: 500,
			port: 8081,
			castName: 'MagicMirror',
		}
	},
```

**Comment by kevinatown** [comment]
Hi @cluelesscarter,

So the issue is that you are using `position: 'middle'` instead of `position: 'center'` for the position of the MMM-Screencast window. Please use `center` and refer to the [config in the readme](https://github.com/kevinatown/MMM-Screencast/blob/master/README.md#configuration-options-for-mmm-screencast).

I should really update this to take either config options 🤦

Good luck!
